<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV0akpiD\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV0akpiD/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerV0akpiD.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerV0akpiD\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerV0akpiD\srcApp_KernelProdContainer([
    'container.build_hash' => 'V0akpiD',
    'container.build_id' => '2578e096',
    'container.build_time' => 1586853685,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV0akpiD');
