<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMCuipDe\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMCuipDe/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerMCuipDe.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerMCuipDe\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerMCuipDe\srcApp_KernelProdContainer([
    'container.build_hash' => 'MCuipDe',
    'container.build_id' => 'e74fcbdc',
    'container.build_time' => 1586251689,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMCuipDe');
