<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAiKxQvS\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAiKxQvS/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerAiKxQvS.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerAiKxQvS\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerAiKxQvS\srcApp_KernelProdContainer([
    'container.build_hash' => 'AiKxQvS',
    'container.build_id' => 'a12b8587',
    'container.build_time' => 1586871035,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAiKxQvS');
