<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'admin' => [[], ['_controller' => 'App\\Controller\\AdminController::index'], [], [['text', '/admin']], [], []],
    'liste_cat' => [[], ['_controller' => 'App\\Controller\\AdminController::listCategory'], [], [['text', '/admin/category']], [], []],
    'add_category' => [[], ['_controller' => 'App\\Controller\\AdminController::createUpdateCategory'], [], [['text', '/admin/category/add']], [], []],
    'update_category' => [['id'], ['_controller' => 'App\\Controller\\AdminController::createUpdateCategory'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/admin/category/add']], [], []],
    'delete_cat' => [['id'], ['_controller' => 'App\\Controller\\AdminController::deleteCategory'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/admin/category']], [], []],
    'liste_product' => [[], ['_controller' => 'App\\Controller\\AdminController::listProduct'], [], [['text', '/admin/product']], [], []],
    'add_product' => [[], ['_controller' => 'App\\Controller\\AdminController::createUpdateProduct'], [], [['text', '/admin/product/add']], [], []],
    'product_update' => [['id'], ['_controller' => 'App\\Controller\\AdminController::createUpdateProduct'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/admin/product/add']], [], []],
    'delete_product' => [['id'], ['_controller' => 'App\\Controller\\AdminController::deleteProduct'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/admin/product']], [], []],
    'details_user' => [['id'], ['_controller' => 'App\\Controller\\AdminController::detailsClient'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/admin/user']], [], []],
    'liste_user' => [[], ['_controller' => 'App\\Controller\\AdminController::listClient'], [], [['text', '/admin/user']], [], []],
    'liste_order' => [[], ['_controller' => 'App\\Controller\\AdminController::listOrder'], [], [['text', '/admin/order']], [], []],
    'details_order_user' => [['id'], ['_controller' => 'App\\Controller\\AdminController::detailsOrderClient'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/admin/order']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\IndexController::listProduct'], [], [['text', '/']], [], []],
    'inscription' => [[], ['_controller' => 'App\\Controller\\IndexController::inscription'], [], [['text', '/inscription']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\IndexController::login'], [], [['text', '/login']], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\IndexController::logout'], [], [['text', '/logout']], [], []],
    'details_product' => [['id'], ['_controller' => 'App\\Controller\\IndexController::detailsProduct'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/index/details']], [], []],
    'add_panier' => [['id'], ['_controller' => 'App\\Controller\\IndexController::addPanier'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/panier/add']], [], []],
    'panier' => [[], ['_controller' => 'App\\Controller\\IndexController::panier'], [], [['text', '/panier/']], [], []],
    'panier_remove' => [['id'], ['_controller' => 'App\\Controller\\IndexController::remove'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/panier/remove']], [], []],
    'order' => [[], ['_controller' => 'App\\Controller\\IndexController::order'], [], [['text', '/order']], [], []],
    'order_confirm' => [[], ['_controller' => 'App\\Controller\\IndexController::orderConfirm'], [], [['text', '/order/confirm']], [], []],
    'compte' => [[], ['_controller' => 'App\\Controller\\IndexController::monCompte'], [], [['text', '/mon_compte']], [], []],
    'update_infos' => [[], ['_controller' => 'App\\Controller\\IndexController::updateInfos'], [], [['text', '/mon_compte/infos']], [], []],
    'update_password' => [[], ['_controller' => 'App\\Controller\\IndexController::updatePassword'], [], [['text', '/mon_compte/password']], [], []],
    'client_order' => [[], ['_controller' => 'App\\Controller\\IndexController::listOrder'], [], [['text', '/client/order']], [], []],
    'details_order' => [['id'], ['_controller' => 'App\\Controller\\IndexController::detailsOrder'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/client/order']], [], []],
];
