<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZxg6BC5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZxg6BC5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZxg6BC5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZxg6BC5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZxg6BC5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Zxg6BC5',
    'container.build_id' => 'f56093d6',
    'container.build_time' => 1586866211,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZxg6BC5');
