<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\AdminController::index'], [], [['text', '/admin']], [], []],
    'liste_cat' => [[], ['_controller' => 'App\\Controller\\AdminController::listCategory'], [], [['text', '/admin/category']], [], []],
    'add_category' => [[], ['_controller' => 'App\\Controller\\AdminController::createUpdateCategory'], [], [['text', '/admin/category/add']], [], []],
    'update_category' => [['id'], ['_controller' => 'App\\Controller\\AdminController::createUpdateCategory'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/admin/category/add']], [], []],
    'delete_cat' => [['id'], ['_controller' => 'App\\Controller\\AdminController::deleteCategory'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/admin/category']], [], []],
    'liste_product' => [[], ['_controller' => 'App\\Controller\\AdminController::listProduct'], [], [['text', '/admin/product']], [], []],
    'add_product' => [[], ['_controller' => 'App\\Controller\\AdminController::createUpdateProduct'], [], [['text', '/admin/product/add']], [], []],
    'product_update' => [['id'], ['_controller' => 'App\\Controller\\AdminController::createUpdateProduct'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/admin/product/add']], [], []],
    'delete_product' => [['id'], ['_controller' => 'App\\Controller\\AdminController::deleteProduct'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/admin/product']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\IndexController::listProduct'], [], [['text', '/']], [], []],
    'inscription' => [[], ['_controller' => 'App\\Controller\\IndexController::inscription'], [], [['text', '/index/login']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\IndexController::login'], [], [['text', '/index/login/1']], [], []],
];
